services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: profile_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - profile-network

  profile-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: profile-service
    environment:
      DB_URL: jdbc:mysql://mysql:3306/profile_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      DB_USERNAME: root
      DB_PASSWORD: root
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8000:8080"
    networks:
      - profile-network
